name: ROS2 CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./skarpulator_desktop_client
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Conditionally remove GPU requirements for CI
      run: |
        yq -i 'del(.services.skarpulator.deploy)' docker-compose.yaml
        yq -i 'del(.services.skarpulator.privileged)' docker-compose.yaml

    - name: Build and run Docker container
      run: docker compose up --build -d

    - name: Run colcon test
      run: docker exec skarpulator bash -c "
          source /opt/ros/jazzy/setup.bash &&
          source /skarpulator/install/setup.bash &&
          colcon test &&
          colcon test-result --all
        "

    - name: Clean up container
      if: always()
      run: docker compose down